env:
  global:
    - CC_TEST_REPORTER_ID=5540b211ab4d3037b213ba53f09165a7eb448abb6e5416275a8795df233d4805
language: ruby
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
rvm:
  - 2.4.1
