urls:
  db: 'postgres://localhost:5432/one_sentence_per_day'
  registration: "http://localhost:4567/register"
  unsubscribe: "http://localhost:4567/unsubscribe"
postmark:
  api_key: <%= ENV["POSTMARK_API_KEY"] %>
paypal:
  client: <%= ENV.fetch("PAYPAL_CLIENT") %>
  secret: <%= ENV.fetch("PAYPAL_SECRET") %>
