urls:
  registration: "https://journmail.com/register"
  unsubscribe: "https://journmail.com/unsubscribe"
  history: "https://journmail.com/history"
paypal:
  client: <%= ENV.fetch("PAYPAL_CLIENT") %>
  secret: <%= ENV.fetch("PAYPAL_SECRET") %>
