urls:
  registration: "https://journmail.com/register"
  unsubscribe: "https://journmail.com/unsubscribe"
  history: "https://journmail.com/history"
  privacy_policy: "https://journmail.com/privacy"
  terms: "https://journmail.com/terms"
paypal:
  client: <%= ENV["PAYPAL_CLIENT"] %>
  secret: <%= ENV["PAYPAL_SECRET"] %>
