urls:
  registration: "https://journmail.com/register"
  unsubscribe: "https://journmail.com/unsubscribe"
  history: "https://journmail.com/history"
paypal:
  client: <%= ENV["PAYPAL_CLIENT"] %>
  secret: <%= ENV["PAYPAL_SECRET"] %>
